#!/usr/bin/env python3
"""
Project Manager Setup Script

Configures the application with your server details and credentials.
"""

import json
import os
import sys


def get_input(prompt, default=None):
    """Get user input with optional default value."""
    if default:
        user_input = input(f"{prompt} [{default}]: ").strip()
        return user_input if user_input else default
    return input(f"{prompt}: ").strip()


def get_password(prompt="Password"):
    """Get password (hidden input)."""
    import getpass
    while True:
        pwd = getpass.getpass(f"{prompt}: ")
        confirm = getpass.getpass(f"Confirm {prompt.lower()}: ")
        if pwd == confirm:
            return pwd
        print("Passwords don't match. Please try again.")


def parse_ssh_config(host_alias):
    """Parse ~/.ssh/config to get host details."""
    ssh_config_path = os.path.expanduser("~/.ssh/config")
    if not os.path.exists(ssh_config_path):
        return None
    
    with open(ssh_config_path, 'r') as f:
        lines = f.readlines()
    
    in_host = False
    config = {}
    
    for line in lines:
        line = line.strip()
        if line.startswith('Host ') and not line.startswith('Host *'):
            host = line.split()[1]
            in_host = (host == host_alias)
        elif in_host and line:
            if line.startswith('HostName '):
                config['hostname'] = line.split()[1]
            elif line.startswith('User '):
                config['user'] = line.split()[1]
            elif line.startswith('Port '):
                config['port'] = int(line.split()[1])
            elif line.startswith('IdentityFile '):
                config['key'] = line.split()[1]
    
    return config if config else None


def main():
    print("=" * 60)
    print("  Project Manager - Setup")
    print("=" * 60)
    print()
    
    # Check if already configured
    if os.path.exists('settings.json'):
        print("Configuration already exists (settings.json found).")
        overwrite = get_input("Overwrite existing configuration? (y/N)", "n")
        if overwrite.lower() != 'y':
            print("Setup cancelled.")
            return
    
    print()
    print("Step 1: Remote Server Configuration")
    print("-" * 40)
    
    # Server connection
    server_input = get_input(
        "Server (IP address, hostname, or SSH alias from ~/.ssh/config)",
        "localhost"
    )
    
    # Check if it's an SSH alias
    ssh_config = parse_ssh_config(server_input)
    
    if ssh_config:
        print(f"  Found '{server_input}' in ~/.ssh/config")
        host = ssh_config.get('hostname', server_input)
        user = ssh_config.get('user', get_input("Username"))
        port = ssh_config.get('port', 22)
        key_path = ssh_config.get('key', '~/.ssh/id_rsa')
    else:
        host = server_input
        user = get_input("Username")
        port = int(get_input("SSH Port", "22"))
        key_path = get_input("SSH Key Path", "~/.ssh/id_rsa")
    
    # Remote projects directory
    print()
    print("Step 2: Projects Directory")
    print("-" * 40)
    print("This is the directory on the remote server that contains your projects.")
    print("The app will only have access to this directory and its subdirectories.")
    print()
    
    remote_path = get_input("Remote projects path (absolute path)", f"/home/{user}/projects")
    
    # Web app credentials
    print()
    print("Step 3: Web Application Credentials")
    print("-" * 40)
    print("These are used to log into the Project Manager web interface.")
    print()
    
    web_user = get_input("Web login username", "admin")
    web_password = get_password("Web login password")
    
    # Generate secret key
    import secrets
    secret_key = secrets.token_hex(32)
    
    # Save settings.json (general settings, no sensitive data)
    settings = {
        "server": {
            "host": host,
            "port": port,
            "user": user,
            "key_path": key_path
        },
        "remote_path": remote_path,
        "web": {
            "host": "0.0.0.0",
            "port": 8000
        }
    }
    
    with open('settings.json', 'w') as f:
        json.dump(settings, f, indent=2)
    
    print("  Created: settings.json")
    
    # Save .credentials.py (sensitive data)
    credentials_content = f'''"""
Credentials for Project Manager - DO NOT COMMIT THIS FILE
This file is auto-generated by setup.py
"""

# Web application credentials
AUTH_USERNAME = {repr(web_user)}
AUTH_PASSWORD = {repr(web_password)}
SECRET_KEY = {repr(secret_key)}
'''
    
    with open('.credentials.py', 'w') as f:
        f.write(credentials_content)
    
    print("  Created: .credentials.py")
    
    # Summary
    print()
    print("=" * 60)
    print("  Setup Complete!")
    print("=" * 60)
    print()
    print("Configuration summary:")
    print(f"  Remote server: {user}@{host}:{port}")
    print(f"  Projects path: {remote_path}")
    print(f"  Web interface: http://localhost:8000")
    print(f"  Login: {web_user}")
    print()
    print("To start the application:")
    print("  ./start.sh")
    print()
    print("To update configuration later, run:")
    print("  python3 setup.py")
    print()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)
